name: Blog Front Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./breeze-web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
      - name: Add wasm build target
        run: rustup target add wasm32-unknown-unknown
      - name: build Rust
        run: trunk build --release
      - name: Switch path
        run: cd dist
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
